name: Run Supabase Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode and write config.json
        run: |
          echo "${{ secrets.CONFIG_JSON_B64 }}" | base64 -d > config.json

      - name: Run script
        run: python main.py
